Repository AllAlgorithms/cpp, pull requests merged in 2020-10, with the labels that each got.

#45 Palindrome for numbers
  palindrome/palindrome_number.cpp
Labels: needs to fixed

#53 Create Sum of all factorials of n!
  The sum of all factorials of n!
Labels: invalid

#102 statusCheck() algorithm
  greedy/readme_statusCheckG.txt
  greedy/sampleInputs.txt
  greedy/statusCheck.cpp
Labels: needs test

#111 added trivial hashing
  data-structures/Trivial Hashing
Labels: invalid, not portable, on hold

#105 Added maxRectangle.cpp
  dynamic-programming/maxRectangle.cpp
Labels: not portable, on hold

#106 preety printing added
  dynamic-programming/pretty_printing.c
Labels: on hold, question

#113 Added Prime or Not
  math/prime_or_not.cpp
Labels: on hold

#42 Longest Increasing Subsequence dp solution
  dynamic-programming/lis.cpp
Labels: merge conflicts

#302 Adding Hamming Code
  algorithms/Networks/Hamming_Code/hamming_code_reciever.cpp
  algorithms/Networks/Hamming_Code/hamming_code_sender.cpp
Labels: on hold
